"""Generate ``docs/kpi_definitions.md`` from a single structured KPI registry.

The registry is the human-readable companion to ``warehouse/kpi.py`` (the
executable definitions) and ``sql/views`` (the BI-facing definitions).
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ..config import REPO_ROOT


@dataclass(frozen=True)
class KPI:
    name: str
    grain: str
    formula: str
    source_tags: str
    owner: str


REGISTRY: list[KPI] = [
    KPI("Throughput", "shift / day / hour",
        "tonnes_milled = Σ(feed_throughput_tph × interval_h)",
        "feed_throughput_tph", "Metallurgy"),
    KPI("Mill availability %", "shift",
        "100 × running_minutes / scheduled_minutes",
        "feed_throughput_tph (running when > 0)", "Operations"),
    KPI("Mill utilization %", "shift",
        "100 × avg_running_throughput / nameplate_tph (OEE performance factor)",
        "feed_throughput_tph", "Operations"),
    KPI("Recovery %", "shift",
        "tonnage-weighted mean of recovery_pct over valid minutes",
        "recovery_pct, feed_throughput_tph", "Metallurgy"),
    KPI("Head grade (g/t)", "shift",
        "tonnage-weighted mean of feed_grade_gpt",
        "feed_grade_gpt, feed_throughput_tph", "Geology"),
    KPI("Tails grade (g/t)", "shift",
        "tonnage-weighted mean of tails_grade_gpt",
        "tails_grade_gpt, feed_throughput_tph", "Metallurgy"),
    KPI("Specific energy (kWh/t)", "shift",
        "Σ(mill_power_kw × interval_h) / tonnes_milled",
        "mill_power_kw, feed_throughput_tph", "Operations"),
    KPI("Cyanide consumption (kg/t)", "shift",
        "tonnage-weighted mean of cyanide_dose_kgpt",
        "cyanide_dose_kgpt, feed_throughput_tph", "Metallurgy"),
    KPI("Lime consumption (kg/t)", "shift",
        "tonnage-weighted mean of lime_dose_kgpt",
        "lime_dose_kgpt, feed_throughput_tph", "Metallurgy"),
    KPI("Gold poured (oz)", "shift / cumulative",
        "Σ gold_poured_oz (per shift), cumulative running total",
        "gold_poured_oz", "Gold Room"),
    KPI("Gold in feed / recovered / tails (oz)", "shift",
        "Σ(tonnes × grade)/31.1035 for each stream; "
        "recovered = feed × recovery; reconciliation: feed ≈ recovered + tails",
        "feed_throughput_tph, feed_grade_gpt, recovery_pct, tails_grade_gpt", "Metallurgy"),
    KPI("OEE-style composite %", "shift",
        "availability × utilization × quality / 10000, "
        "quality = % Good historian flags",
        "all of the above + quality_flag", "Operations"),
]


def generate(out_path: Path | None = None) -> Path:
    out = out_path or (REPO_ROOT / "docs" / "kpi_definitions.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# KPI Definitions",
        "",
        "_Generated by `python -m mill docs`. Executable definitions live in "
        "`src/mill/warehouse/kpi.py`; BI-facing copies in `sql/views`._",
        "",
        "| KPI | Grain | Formula | Source tags | Owner |",
        "| --- | --- | --- | --- | --- |",
    ]
    for k in REGISTRY:
        lines.append(f"| {k.name} | {k.grain} | {k.formula} | {k.source_tags} | {k.owner} |")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
